/*
 * core/furniture/list.pwn TOMAS VOSYLIUS
 */


#define FURNITURE_CATEGORY_FRIDGES 				0
#define FURNITURE_CATEGORY_HEAT 				1
#define FURNITURE_CATEGORY_BINS 				2
#define FURNITURE_CATEGORY_CONTAINER 			3
#define FURNITURE_CATEGORY_KITCHEN_ELECTRONICS 	4
#define FURNITURE_CATEGORY_BEDS 				5
#define FURNITURE_CATEGORY_CHAIRS 				6
#define FURNITURE_CATEGORY_ARMCHAIRS 			7
#define FURNITURE_CATEGORY_COUCHES 				8
#define FURNITURE_CATEGORY_CURTAINS 			9
#define FURNITURE_CATEGORY_FLAGS 				10
#define FURNITURE_CATEGORY_CARPETS 				11
#define FURNITURE_CATEGORY_STATUES 				12
#define FURNITURE_CATEGORY_TOWELS 				13
#define FURNITURE_CATEGORY_PAINTINGS 			14
#define FURNITURE_CATEGORY_PLANTS 				15
#define FURNITURE_CATEGORY_SPORTS 				16
#define FURNITURE_CATEGORY_TV 					17
#define FURNITURE_CATEGORY_PC 					18
#define FURNITURE_CATEGORY_PLAYERS 				19
#define FURNITURE_CATEGORY_AUDIO 				20
#define FURNITURE_CATEGORY_LAMPS 				21
#define FURNITURE_CATEGORY_CLOTHES 				22
#define FURNITURE_CATEGORY_BOTTLES 				23
#define FURNITURE_CATEGORY_DOORS 				24
#define FURNITURE_CATEGORY_TRASH 				25
#define FURNITURE_CATEGORY_OTHER 				26
#define FURNITURE_CATEGORY_COLONIES 			27
#define FURNITURE_CATEGORY_SAFETY 				28
#define FURNITURE_CATEGORY_OFFICE 				29
#define FURNITURE_CATEGORY_TOYS 				30
#define FURNITURE_CATEGORY_PETS 				31
#define FURNITURE_CATEGORY_PARTIES 				32
#define FURNITURE_CATEGORY_GAMBLING 			33
#define FURNITURE_CATEGORY_GRAFFITI 			34
#define FURNITURE_CATEGORY_WALLS 				35
#define FURNITURE_CATEGORY_TABLES 				36
#define FURNITURE_CATEGORY_PLUMBING 			37
#define FURNITURE_CATEGORY_STORAGE 				38

new const FurnitureCategories[][32] = {
	/* FURNITURE_CATEGORY_FRIDGES */ {"Saldytuvai"},
	/* FURNITURE_CATEGORY_HEAT */ {"Krosnys, Sildytuvai"},
	/* FURNITURE_CATEGORY_BINS */ {"SiukSliadeZes"},
	/* FURNITURE_CATEGORY_CONTAINER */ {"Konteineriai"},
	/* FURNITURE_CATEGORY_KITCHEN_ELECTRONICS */ {"Virtuves prietaisai"},
	/* FURNITURE_CATEGORY_BEDS */ {"Lovos"},
	/* FURNITURE_CATEGORY_CHAIRS */ {"Kedes"},
	/* FURNITURE_CATEGORY_ARMCHAIRS */ {"Kreslai"},
	/* FURNITURE_CATEGORY_COUCHES */ {"Sofos"},
	/* FURNITURE_CATEGORY_CURTAINS */ {"UZuolaidos"},
	/* FURNITURE_CATEGORY_FLAGS */ {"Veliavos"},
	/* FURNITURE_CATEGORY_CARPETS */ {"Kilimai"},
	/* FURNITURE_CATEGORY_STATUES */ {"Statulos"},
	/* FURNITURE_CATEGORY_TOWELS */ {"RankSluoSCiai"},
	/* FURNITURE_CATEGORY_PAINTINGS */ {"Paveikslai"},
	/* FURNITURE_CATEGORY_PLANTS */ {"Augalija"},
	/* FURNITURE_CATEGORY_SPORTS */ {"Sporto inventorius"},
	/* FURNITURE_CATEGORY_TV */ {"Televizoriai"},
	/* FURNITURE_CATEGORY_PC */ {"Kompiuterija"},
	/* FURNITURE_CATEGORY_PLAYERS */ {"Grotuvai"},
	/* FURNITURE_CATEGORY_AUDIO */ {"Audio"},
	/* FURNITURE_CATEGORY_LAMPS */ {"Sviestuvai"},
	/* FURNITURE_CATEGORY_CLOTHES */ {"DrabuZiai"},
	/* FURNITURE_CATEGORY_BOTTLES */ {"Buteliai"},
	/* FURNITURE_CATEGORY_DOORS */ {"Durys"},
	/* FURNITURE_CATEGORY_TRASH */ {"SiukSles"},
	/* FURNITURE_CATEGORY_OTHER */ {"Kita"},
	/* FURNITURE_CATEGORY_COLONIES */ {"Kolonos"},
	/* FURNITURE_CATEGORY_SAFETY */ {"Apsaugos, kameros, alarm"},
	/* FURNITURE_CATEGORY_OFFICE */ {"Ofiso inventorius"},
	/* FURNITURE_CATEGORY_TOYS */ {"Zaislai"},
	/* FURNITURE_CATEGORY_PETS */ {"GyvUnija"},
	/* FURNITURE_CATEGORY_PARTIES */ {"Vakareliø inventorius"},
	/* FURNITURE_CATEGORY_GAMBLING */ {"LoSimø inventorius"},
	/* FURNITURE_CATEGORY_GRAFFITI */ {"Graffiti"},
	/* FURNITURE_CATEGORY_WALLS */ {"Sienos"},
	/* FURNITURE_CATEGORY_TABLES */ {"Stalai"},
	/* FURNITURE_CATEGORY_PLUMBING */ {"Santechnika"},
	/* FURNITURE_CATEGORY_STORAGE */ {"Sandeliavimas"}
};